easy:
  no-repeat-submit:
    enable: true
    timeout: 1500
  log:
    enable: true
    request-save-max-length: 1000
    response-save-max-length: 1000
    error-save-max-length: 1000
    filter:
      fields: password,token,salt,oldPassword,newPassword
  lock:
    lease-time: 30
    wait-time: 5
  file:
    prefix: 127.0.0.1:${server.port}
    file-map-path: /file
    image-map-path: /image
    max-file-size: 10
    max-image-size: 10
    file-type: doc,docx,ppt,pptx,wps,xls,xlsx,pdf
    image-type: jpg,jpeg,png,gif,ico,svg


server:
  # 端口号
  port: 9000
  servlet:
    # 接口访问路径
    contextPath: /
  # springboot 2.3新特性，优雅停机，注意不要使用kill -9 ，使用kill -2 才能触发
  shutdown: GRACEFUL

#spring配置
spring:
  servlet:
    # 不在这里限制最大文件上传大小
    multipart:
      # 单个文件上传大小限制
      max-file-size: 20MB
      # 总请求大小限制
      max-request-size: 100MB
  profiles:
    # 指定配置文件
    active: dev
  lifecycle:
    # 优雅停机等待时长
    timeout-per-shutdown-phase: 10s
  quartz:
    # 将任务保存化到数据库
    job-store-type: jdbc
    # 程序结束时会等待quartz相关的内容结束
    wait-for-jobs-to-complete-on-shutdown: true
    # QuartzScheduler启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          # scheduler相关
          scheduler:
            # scheduler的实例名
            instance-name: EasyScheduler
            instance-id: AUTO
          # 持久化相关
          job-store:
            # 最大能忍受的触发超时时间/ms
            misfire-threshold: 30000
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driver-delegate-class: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # 表示数据库中相关表是QRTZ_开头的
            table-prefix: QRTZ_
            use-properties: false
            #设置此实例“检入”*与群集的其他实例的频率（以毫秒为单位）。影响检测失败实例的速度。
            cluster-checkin-interval: 5000
            # 是否开启集群功能,开启集群只需要配置相同的 instanceName 实例名称
            is-clustered: false
          # 线程池相关
          thread-pool:
            class: org.quartz.simpl.SimpleThreadPool
            # 线程数
            thread-count: 10
            # 线程优先级
            thread-priority: 5
            threads-inherit-context-class-loader-of-initializing-thread: true


# 配置文档 https://baomidou.com/#tablename
mybatis-plus:
  type-aliases-package: cn.easy.boot.admin.user.dos.*
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启数据库字段驼峰式命名映射
    map-underscore-to-camel-case: true
  global-config:
    # 限制分页最高条数
    max-limit: 2000
    # 关闭控制台 mybatis-plus logo打印
    banner: false
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 逻辑删除 - 未删除
      logic-not-delete-value: 0
      # 逻辑删除 - 已删除
      logic-delete-value: 1

springdoc:
  swagger-ui:
    enabled: true
    #swagger后端访问地址
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    #是否开启文档功能
    enabled: ${springdoc.swagger-ui.enabled}
    path: /v3/api-docs
  group-configs:
    - group: 后台管理接口
      paths-to-match: /**
      packages-to-scan: cn.easy.boot.admin
  default-flat-param-object: true

# 配置文档 https://doc.xiaominfo.com/docs/features/enhance
knife4j:
  enable: ${springdoc.swagger-ui.enabled}
  setting:
    enable-footer: false
    enable-footer-custom: true
    swagger-model-name: 实体类列表
    footer-custom-content: Copyright © 2023-2026 easyboot.cn 版权所有.(https://gitee.com/thisZhuMy_admin/easy-boot-v3)

captcha:
  prefix: easy:boot:captcha
  # 验证码过期时间，默认是2分钟,单位毫秒， 可以根据自身业务进行调整
  expire:
    # 默认缓存时间 2分钟
    default: 60000
    # 针对 点选验证码 过期时间设置为 2分钟， 因为点选验证码验证比较慢，把过期时间调整大一些
    WORD_IMAGE_CLICK: 60000
  # 使用加载系统自带的资源， 默认是 false
  init-default-resource: false
  cache:
    # 缓存控制， 默认为false不开启
    enabled: true
    # 验证码会提前缓存一些生成好的验证数据， 默认是20
    cacheSize: 200
    # 缓存拉取失败后等待时间 默认是 5秒钟
    wait-time: 5000
    # 缓存检查间隔 默认是2秒钟
    period: 2000
  secondary:
    # 二次验证， 默认false 不开启
    enabled: false
    # 二次验证过期时间， 默认 2分钟
    expire: 120000
    # 二次验证缓存key前缀，默认是 captcha:secondary
    key-prefix: easy:boot:captcha:secondary