pipeline {
    agent any
    environment {
        MVN_HOME = "/Users/zoe/Desktop/开发工具/maven/apache-maven-3.6.3"
        PATH = "$MVN_HOME/bin:$PATH"
    }
    stages {
        // 切代码分支 可省略这一步
        //stage('拉取代码') {
            //steps {
                //git branch: 'master', credentialsId: '117af67f-3976-4b81-a718-ce31c685170f', url: 'https://gitee.com/thisZhuMy_admin/EasyBoot.git'
            //}
        //}
        stage('编译构建') {
            steps {
                sh "mvn clean package -Dmaven.test.skip=true"
            }
        }
    }
    post {
        success {
            echo '上传jar包和脚本'
            sshPublisher(publishers: [sshPublisherDesc(configName: '本人服务器', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'sh /data/java/easy.sh backup', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '', remoteDirectorySDF: false, removePrefix: 'script', sourceFiles: 'script/easy.sh'), sshTransfer(cleanRemote: false, excludes: '', execCommand: 'nohup sh /data/java/easy.sh restart > /dev/null 2>&1 &', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '', remoteDirectorySDF: false, removePrefix: 'target', sourceFiles: 'target/EasyBoot.jar')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: true)])
        }
    }
}